/*
 * Created on Tue Oct 25 2022
 * Copyright (c) 2022 Connor Doman
 */

export const TEST_USERS = [
    {
        uniqueID: "wvc8r",
        firstName: "Mary",
        lastName: "Garcia",
        email: "mary.garcia@example.com",
        permission: 5,
    },
    {
        uniqueID: "enNLU",
        firstName: "Sara",
        lastName: "Johnson",
        email: "sara.johnson@example.com",
        permission: 2,
    },
    {
        uniqueID: "vlctV",
        firstName: "Mary",
        lastName: "Davis",
        email: "mary.davis@example.com",
        permission: 3,
    },
    {
        uniqueID: "qLxjM",
        firstName: "Sara",
        lastName: "Rodriguez",
        email: "sara.rodriguez@example.com",
        permission: 4,
    },
    {
        uniqueID: "1RXqn",
        firstName: "Sara",
        lastName: "Davis",
        email: "sara.davis@example.com",
        permission: 5,
    },
    {
        uniqueID: "fL5CX",
        firstName: "Sally",
        lastName: "Wilson",
        email: "sally.wilson@example.com",
        permission: 1,
    },
    {
        uniqueID: "RANnn",
        firstName: "Tom",
        lastName: "Davis",
        email: "tom.davis@example.com",
        permission: 2,
    },
    {
        uniqueID: "lYQ3e",
        firstName: "Sally",
        lastName: "Jones",
        email: "sally.jones@example.com",
        permission: 2,
    },
    {
        uniqueID: "PVGJL",
        firstName: "Joe",
        lastName: "Brown",
        email: "joe.brown@example.com",
        permission: 5,
    },
    {
        uniqueID: "qmmGU",
        firstName: "Bob",
        lastName: "Smith",
        email: "bob.smith@example.com",
        permission: 1,
    },
    {
        uniqueID: "xxEPC",
        firstName: "Tom",
        lastName: "Wilson",
        email: "tom.wilson@example.com",
        permission: 0,
    },
    {
        uniqueID: "mhaaF",
        firstName: "Sara",
        lastName: "Jones",
        email: "sara.jones@example.com",
        permission: 2,
    },
    {
        uniqueID: "Ynfbq",
        firstName: "Jane",
        lastName: "Rodriguez",
        email: "jane.rodriguez@example.com",
        permission: 4,
    },
    {
        uniqueID: "OZIyh",
        firstName: "Sue",
        lastName: "Davis",
        email: "sue.davis@example.com",
        permission: 5,
    },
    {
        uniqueID: "NnN5T",
        firstName: "Sally",
        lastName: "Jones",
        email: "sally.jones@example.com",
        permission: 3,
    },
    {
        uniqueID: "b7yy4",
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.johnson@example.com",
        permission: 1,
    },
    {
        uniqueID: "wzrwn",
        firstName: "Sally",
        lastName: "Rodriguez",
        email: "sally.rodriguez@example.com",
        permission: 1,
    },
    {
        uniqueID: "VQdBp",
        firstName: "Joe",
        lastName: "Johnson",
        email: "joe.johnson@example.com",
        permission: 1,
    },
    {
        uniqueID: "rcHkG",
        firstName: "Jane",
        lastName: "Brown",
        email: "jane.brown@example.com",
        permission: 5,
    },
    {
        uniqueID: "ziKt4",
        firstName: "Sara",
        lastName: "Smith",
        email: "sara.smith@example.com",
        permission: 0,
    },
    {
        uniqueID: "wIRjl",
        firstName: "Jane",
        lastName: "Jones",
        email: "jane.jones@example.com",
        permission: 4,
    },
    {
        uniqueID: "1uGOl",
        firstName: "Tom",
        lastName: "Miller",
        email: "tom.miller@example.com",
        permission: 0,
    },
    {
        uniqueID: "BJeyu",
        firstName: "Sally",
        lastName: "Brown",
        email: "sally.brown@example.com",
        permission: 3,
    },
];

export default TEST_USERS;
