/*
 * Created on Wed Oct 26 2022
 * Copyright (c) 2022 Connor Doman
 */

export const TEST_USERS = [
    {
        uniqueID: "574d9e24",
        firstName: "Alice",
        lastName: "Smith",
        email: "alice.smith@example.com",
        permission: 5,
    },
    {
        uniqueID: "be68a08f",
        firstName: "Joe",
        lastName: "Johnson",
        email: "joe.johnson@example.com",
        permission: 1,
    },
    {
        uniqueID: "8c077935",
        firstName: "Sue",
        lastName: "Williams",
        email: "sue.williams@example.com",
        permission: 2,
    },
    {
        uniqueID: "cab98db5",
        firstName: "Connor",
        lastName: "Doman",
        email: "c.doman@me.com",
        permission: 2,
    },
    {
        uniqueID: "5bf022cb",
        firstName: "Sara",
        lastName: "Wilson",
        email: "sara.wilson@example.com",
        permission: 4,
    },
    {
        uniqueID: "29a5bf5b",
        firstName: "John",
        lastName: "Miller",
        email: "john.miller@example.com",
        permission: 2,
    },
    {
        uniqueID: "b14989e8",
        firstName: "Bob",
        lastName: "Brown",
        email: "bob.brown@example.com",
        permission: 4,
    },
    {
        uniqueID: "aae4c529",
        firstName: "Sue",
        lastName: "Smith",
        email: "sue.smith@example.com",
        permission: 2,
    },
    {
        uniqueID: "10fae363",
        firstName: "Bob",
        lastName: "Miller",
        email: "bob.miller@example.com",
        permission: 4,
    },
    {
        uniqueID: "98d5644d",
        firstName: "Mary",
        lastName: "Brown",
        email: "mary.brown@example.com",
        permission: 0,
    },
    {
        uniqueID: "56ffcfcf",
        firstName: "Sue",
        lastName: "Wilson",
        email: "sue.wilson@example.com",
        permission: 4,
    },
    {
        uniqueID: "8fe7bb53",
        firstName: "Sue",
        lastName: "Rodriguez",
        email: "sue.rodriguez@example.com",
        permission: 2,
    },
    {
        uniqueID: "1eb1f9b3",
        firstName: "Sue",
        lastName: "Miller",
        email: "sue.miller@example.com",
        permission: 0,
    },
    {
        uniqueID: "dae17806",
        firstName: "Bob",
        lastName: "Miller",
        email: "bob.miller@example.com",
        permission: 2,
    },
    {
        uniqueID: "e4b43c3f",
        firstName: "Bob",
        lastName: "Smith",
        email: "bob.smith@example.com",
        permission: 0,
    },
    {
        uniqueID: "a5f6d71c",
        firstName: "Tom",
        lastName: "Miller",
        email: "tom.miller@example.com",
        permission: 3,
    },
    {
        uniqueID: "be32e85f",
        firstName: "Joe",
        lastName: "Wilson",
        email: "joe.wilson@example.com",
        permission: 4,
    },
    {
        uniqueID: "088d5cb3",
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.johnson@example.com",
        permission: 0,
    },
    {
        uniqueID: "5c8b2fdc",
        firstName: "Sally",
        lastName: "Williams",
        email: "sally.williams@example.com",
        permission: 2,
    },
    {
        uniqueID: "4675ab54",
        firstName: "Joe",
        lastName: "Davis",
        email: "joe.davis@example.com",
        permission: 3,
    },
    {
        uniqueID: "e1bfa1c2",
        firstName: "Tom",
        lastName: "Wilson",
        email: "tom.wilson@example.com",
        permission: 2,
    },
    {
        uniqueID: "b3fd5fd5",
        firstName: "Sally",
        lastName: "Garcia",
        email: "sally.garcia@example.com",
        permission: 2,
    },
    {
        uniqueID: "42fba00e",
        firstName: "Bob",
        lastName: "Johnson",
        email: "bob.johnson@example.com",
        permission: 5,
    },
    {
        uniqueID: "30d56746",
        firstName: "Joe",
        lastName: "Rodriguez",
        email: "joe.rodriguez@example.com",
        permission: 5,
    },
    {
        uniqueID: "7aa29853",
        firstName: "Jane",
        lastName: "Johnson",
        email: "jane.johnson@example.com",
        permission: 2,
    },
    {
        uniqueID: "f8443d03",
        firstName: "Jane",
        lastName: "Brown",
        email: "jane.brown@example.com",
        permission: 3,
    },
    {
        uniqueID: "451a1b6a",
        firstName: "Joe",
        lastName: "Jones",
        email: "joe.jones@example.com",
        permission: 4,
    },
    {
        uniqueID: "a8ee5d13",
        firstName: "Sara",
        lastName: "Miller",
        email: "sara.miller@example.com",
        permission: 3,
    },
    {
        uniqueID: "f7f61c10",
        firstName: "Joe",
        lastName: "Miller",
        email: "joe.miller@example.com",
        permission: 0,
    },
    {
        uniqueID: "6b45c9ba",
        firstName: "Sara",
        lastName: "Brown",
        email: "sara.brown@example.com",
        permission: 2,
    },
    {
        uniqueID: "b41f0795",
        firstName: "Tom",
        lastName: "Brown",
        email: "tom.brown@example.com",
        permission: 5,
    },
    {
        uniqueID: "e4c450d8",
        firstName: "Bob",
        lastName: "Johnson",
        email: "bob.johnson@example.com",
        permission: 0,
    },
    {
        uniqueID: "10eb0f13",
        firstName: "John",
        lastName: "Wilson",
        email: "john.wilson@example.com",
        permission: 0,
    },
    {
        uniqueID: "e7916f51",
        firstName: "Sue",
        lastName: "Wilson",
        email: "sue.wilson@example.com",
        permission: 1,
    },
    {
        uniqueID: "6158a4b8",
        firstName: "Joe",
        lastName: "Brown",
        email: "joe.brown@example.com",
        permission: 3,
    },
    {
        uniqueID: "7a1664d7",
        firstName: "Bob",
        lastName: "Johnson",
        email: "bob.johnson@example.com",
        permission: 3,
    },
    {
        uniqueID: "1abf5e9f",
        firstName: "Tom",
        lastName: "Wilson",
        email: "tom.wilson@example.com",
        permission: 1,
    },
    {
        uniqueID: "366f12bd",
        firstName: "Joe",
        lastName: "Smith",
        email: "joe.smith@example.com",
        permission: 2,
    },
    {
        uniqueID: "0ade8d93",
        firstName: "Jane",
        lastName: "Garcia",
        email: "jane.garcia@example.com",
        permission: 1,
    },
    {
        uniqueID: "9557e976",
        firstName: "Sue",
        lastName: "Johnson",
        email: "sue.johnson@example.com",
        permission: 1,
    },
    {
        uniqueID: "922e3457",
        firstName: "Sue",
        lastName: "Miller",
        email: "sue.miller@example.com",
        permission: 0,
    },
    {
        uniqueID: "fd093a7c",
        firstName: "John",
        lastName: "Johnson",
        email: "john.johnson@example.com",
        permission: 3,
    },
    {
        uniqueID: "49c0fe5c",
        firstName: "Tom",
        lastName: "Williams",
        email: "tom.williams@example.com",
        permission: 1,
    },
    {
        uniqueID: "fefc8160",
        firstName: "Sally",
        lastName: "Garcia",
        email: "sally.garcia@example.com",
        permission: 4,
    },
    {
        uniqueID: "ea50794d",
        firstName: "John",
        lastName: "Rodriguez",
        email: "john.rodriguez@example.com",
        permission: 3,
    },
    {
        uniqueID: "25957fc0",
        firstName: "Joe",
        lastName: "Jones",
        email: "joe.jones@example.com",
        permission: 5,
    },
    {
        uniqueID: "95d6dae4",
        firstName: "Alice",
        lastName: "Rodriguez",
        email: "alice.rodriguez@example.com",
        permission: 3,
    },
    {
        uniqueID: "a5ed1aac",
        firstName: "Tom",
        lastName: "Jones",
        email: "tom.jones@example.com",
        permission: 3,
    },
    {
        uniqueID: "679f19a1",
        firstName: "Mary",
        lastName: "Miller",
        email: "mary.miller@example.com",
        permission: 1,
    },
    {
        uniqueID: "7801d895",
        firstName: "Joe",
        lastName: "Jones",
        email: "joe.jones@example.com",
        permission: 2,
    },
];

export default TEST_USERS;
